DROP DATABASE IF EXISTS SQL_STORE ;
CREATE DATABASE IF NOT EXISTS SQL_STORE;
USE SQL_STORE;
DROP TABLE IF EXISTS department ;
DROP TABLE IF EXISTS role ;
DROP TABLE IF EXISTS employee ;


CREATE TABLE IF NOT EXISTS department 
(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30)
);


CREATE TABLE IF NOT EXISTS role (
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(30),
salary DECIMAL,
department_id INT,
FOREIGN KEY (department_id)
REFERENCES department (id)
ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS employee (
id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(30),
last_name VARCHAR(30),
role_id INT,
manager_id INT,
FOREIGN KEY (manager_id)
REFERENCES employee(id)
ON DELETE SET NULL,
FOREIGN KEY (role_id)
REFERENCES role(id)
ON DELETE SET NULL
);